import NavBar from "./NavBar";
import style from "../styles/Layout.module.scss";
import Head from "next/head";
const Layout = ({ children, title }: { children: React.ReactNode, title?:string }) => {
  return (
    <>
    <Head>
        <title>{ title || "Minos"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Golos+Text&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>
    <div className={style.layout}>
      <NavBar />
       <div className={style.container}>
        {children}
      </div>
    </div>
    </>
  );
};

export default Layout;
